#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Views for the export app."""
import os

from django.http import HttpResponse

from export.models import ExportDocument


def index(request):
    """Export cv to word document.

    :param request: HttpRequest object for export_docx page.
    :type request: object
    :return: Word document generated by export module.
    :rtype: object
    """
    stream = ExportDocument().export(1)

    # Special thanks to: https://stackoverflow.com/a/24122313

    length = stream.tell()
    stream.seek(0)
    response = HttpResponse(
        stream.getvalue(),
        content_type=(
            "application/vnd.openxmlformats-officedocument."
            "wordprocessingml.document"
        )
    )
    response['Content-Disposition'] = (
        'attachment; filename={0}-cv.docx'.format(os.environ.get('RSUM_ENV'))
    )
    response['Content-Length'] = length
    return response
