#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Views for the rsum home application."""
import json
from collections import OrderedDict

from django.shortcuts import render
from django.db import models
from django.http import HttpResponse
from django.conf import settings

import models
# from export.word import ExportDocument

section = models.section.Section


def index(request):
    """Method for loading the index page.

    :param request: `django.http.HttpRequest` object for index page.
    :type request: object 
    :return: HttpResponse object resulting from execution of render method.
    :rtype: object 
    """

    profile = models.profile.Profile.objects.get(name=settings.OWNER)

    sections = OrderedDict() 
    sections_query = section.objects.values() 
    for section_item in sections_query:
        sections.update({
            section_item.get('name'): json.loads(section_item.get('content'))
        })

    context = {
        'profile': profile.name,
        'sections': sections,
    } 
         
    return render(request, 'home/index.html', context)

def export_docx(request, cv_id='1'):
    """Method for exporting Word documents.

    :param request: HttpRequest object for export_docx page.
    :type request: object 
    :return: Word document generated by export module.
    :rtype: object
    stream = ExportDocument().export(cv_id)

    # Special thanks to: https://stackoverflow.com/a/24122313 

    length = stream.tell()
    stream.seek(0)
    response = HttpResponse(
        stream.getvalue(),
        content_type='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    )
    response['Content-Disposition'] = 'attachment; filename={0}-cv.docx'.format(settings.OWNER)
    response['Content-Length'] = length
    return response 

    """
    return render(request, 'home/index.html', {}) 
