---
language: python
sudo: required
env:
  global:
  - CC_TEST_REPORTER_ID=0c3e89da1f412234cef496030b36ec04ca246e2ca82f6a1a5bf7c523a05380a3
cache:
  pip: 'yes'
addons:
  apt:
    sources:
      - sourceline:
          'deb http://cz.archive.ubuntu.com/ubuntu xenial main universe'
    packages:
      - build-essential
before_install:
  - openssl aes-256-cbc -K $encrypted_88341752b148_key
      -iv $encrypted_88341752b148_iv
      -in files/deploy/deploy.enc -out files/deploy/deploy -d
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - "./cc-test-reporter before-build"
  - sudo pip install virtualenv
  - virtualenv -p /usr/bin/python3 .py
  - source .py/bin/activate
  - .py/bin/pip install requests
  - .py/bin/pip install pyyaml
  - .py/bin/pip install django
  - .py/bin/pip install git+https://github.com/metacloud/molecule.git
  - .py/bin/pip install git+https://github.com/docker/docker-py.git
  - .py/bin/pip install psycopg2
  - .py/bin/pip install coverage 
  - ".py/bin/pip install pytest"
  - ".py/bin/pip install nose"
script:
  - ".py/bin/pytest || true"
  - cd files/rsum/rsum
  - "../../../.py/bin/pytest || true"
  - ../../../.py/bin/nosetests -s -d -v
  - coverage run setup.py test 
  - coverage xml
  - cp coverage.xml ../../coverage.xml
  - cd ../../
  - molecule test
after_script:
  - "./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT"
  - "./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT modules/humanresources/coverage.xml"
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
on_success: never
on_failure: never
services:
  docker
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: chmod 600 files/deploy/deploy &&
#     ssh -o StrictHostKeyChecking=no -i files/deploy/deploy
#     duchess@ecla.solutions /src/rsum/files/deploy/deploy.bash
#   "on":
#     branch: master
...
# vim: ft=ansible:
