---
sudo: required
language: python
dist: xenial
services:
  - docker
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ansible
  - ansible -m apt_repository -a
      'repo="
        deb http://cz.archive.ubuntu.com/ubuntu xenial main universe
      "
      state=present'
    -s localhost
  - ansible -m apt -a 'update_cache=yes' -s localhost
  - sudo apt-get install docker.io
  - sudo apt-get install gcc
  - sudo apt-get install build-essential
install:
  - pip install git+https://github.com/metacloud/molecule.git 
  - pip install git+https://github.com/docker/docker-py.git
  - pip install ansible-container
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
# vim: ft=ansible:
