---
language: python
sudo: required
env:
  global:
cache:
  pip: 'yes'
before_script:
  - sudo apt-get -y install build-essential
  - docker network create rsum || true
  - mkdir /tmp/pg
  - docker pull postgres:alpine
  - docker run --user postgres -v /tmp/pg:/var/lib/postgresql:rw >
      --network rsum --expose 5432 -h pg.gc --name pg.gc --rm -d
      postgres:alpine postgres -D /var/lib/postgresql/data
script:
  - cd container
  - docker build -t rsum .
  - cd ..
  - docker run -e CODACY_PROJECT_TOKEN=a6401ae2caa54f229e65b73ec1863ef1 >
      --network rsum -d --name rsum --rm rsum
  - docker exec pg.gc createuser -s xander
  - docker exec rsum cc-test-reporter before-build
  - docker exec rsum pytest rsum/home/tests/models/test_section.py
  - docker exec rsum pytest rsum/home/tests/models/test_profile.py
  - docker exec rsum coverage run setup.py test || true
  - docker exec rsum coverage xml || true
  - docker exec rsum cc-test-reporter after-build -t coverage.py >
      --exit-code $TRAVIS_TEST_RESULT
  - docker exec rsum python-codacy-coverage -r coverage.xml
after_script:
  - docker stop rsum
...
