---
language: python
sudo: required
cache:
  pip: 'yes'
  yarn: 'yes'
addons:
  apt:
    sources:
      - sourceline: 
          'deb http://cz.archive.ubuntu.com/ubuntu xenial main universe'
    packages:
      - build-essential
before_install:
  - openssl aes-256-cbc -K $encrypted_88341752b148_key
      -iv $encrypted_88341752b148_iv
      -in files/deploy/deploy.enc -out files/deploy/deploy -d
install:
  - pip install git+https://github.com/metacloud/molecule.git
  - pip install git+https://github.com/docker/docker-py.git
  - pip install psycopg2
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 files/deploy/deploy &&
    ssh -o StrictHostKeyChecking=no -i files/deploy/deploy
    duchess@ecla.solutions /src/rsum/files/deploy/deploy.bash
  "on":
    branch: master
on_success: never
on_failure: never
services:
  docker
...
# vim: ft=ansible:
