---
language: python
sudo: required
cache:
  pip: 'yes'
  yarn: 'yes'
addons:
  apt:
    sources:
      - sourceline:
          'deb http://cz.archive.ubuntu.com/ubuntu xenial main universe'
    packages:
      - build-essential
before_install:
  - openssl aes-256-cbc -K $encrypted_88341752b148_key
      -iv $encrypted_88341752b148_iv
      -in files/deploy/deploy.enc -out files/deploy/deploy -d
install:
  - pip install git+https://github.com/metacloud/molecule.git
  - pip install git+https://github.com/docker/docker-py.git
  - pip install psycopg2
  - pip install coverage
env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - coverage run files/rsum/rsum/manage.py test || true 
  - coverage xml
  - molecule test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
on_success: never
on_failure: never
services:
  docker
# deploy:
#   provider: script
#   skip_cleanup: true
#   script: chmod 600 files/deploy/deploy &&
#     ssh -o StrictHostKeyChecking=no -i files/deploy/deploy
#     duchess@ecla.solutions /src/rsum/files/deploy/deploy.bash
#   "on":
#     branch: master
...
