---
sudo: required
language: python
dist: xenial
before_install:
  - openssl aes-256-cbc -K
      $encrypted_356f2db0507c_key -iv
      $encrypted_356f2db0507c_iv -in
      files/deploy.enc -out files/deploy -d
  - sudo apt-get -qq update
  - sudo apt-get install ansible
  - ansible -m apt_repository -a 'repo="
      deb http://cz.archive.ubuntu.com/ubuntu xenial main universe
    " state=present' -s localhost
  - ansible -m apt -a 'update_cache=yes' -s localhost
  - ansible -m apt -a 'name=docker.io state=latest' -s localhost
  - sudo apt-get install gcc
  - sudo apt-get install build-essential
install:
  - pip install git+https://github.com/metacloud/molecule.git
  - pip install git+https://github.com/docker/docker-py.git
  - pip install ansible-container
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 files/deploy &&
    ssh -o StrictHostKeyChecking=no -i files/deploy.pub
    duchess@ecla.solutions '/src/rsum/files/deploy.bash'
  "on":
    branch: iss53
...
# vim: ft=ansible:
