---
- name: "Debug current working directory."
  debug:
    var: current_directory
- name: "Set directories for all others."
  set_fact:
    dirs:
      "{{
        lookup(
          'pipe',
          'ls -1 ../../../files/rsum/cvs/'
        ).split('\n') | list
      }}"
  when: inventory_hostname != 'mrsum'
- name: "Set directories for molecule."
  set_fact:
    mdirs:
      "{{
        lookup(
          'pipe',
          'ls -1 ../../files/rsum/cvs/'
        ).split('\n') | list
      }}"
  when: inventory_hostname == 'mrsum'
- name: "Define filenames for molecule."
  set_fact:
    '{{ item }}':
      "{{ lookup(
        'pipe',
        'ls -1 ../../files/rsum/cvs/'+item+'/'
      ).split('\n') | list }}"
  with_items: "{{ mdirs }}"
  when: inventory_hostname == 'mrsum'
- name: "Define filenames for all others."
  set_fact:
    '{{ item }}':
      "{{ lookup(
        'pipe',
        'ls -1 ../../../files/rsum/cvs/'+item+'/'
      ).split('\n') | list }}"
  with_items: "{{ dirs }}"
  when: inventory_hostname != 'mrsum'
...
# vim: ft=ansible:
