---
- name: "Install git-completion.bash."
  get_url:
    url: "http://bit.ly/2tB6adK"
    dest: "/root/.git-completion.bash"
- name: "Install some packages with pip."
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - django
- name: "Install some packages with apt."
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gunicorn
    - vim
- name: "Start a django project."
  command: "/usr/local/bin/django-admin startproject rsum"
  args:
    creates: "/srv/rsum/rsum"
    chdir: "/srv/rsum"
- name: "Create an app in the new project."
  command: "/srv/rsum/rsum/manage.py startapp home"
  args:
    creates: "/srv/rsum/rsum/home"
    chdir: "/srv/rsum/rsum/"
- name: "Run migrations."
  django_manage:
    app_path: "/srv/rsum/rsum"
    command: "syncdb"
...
# vim: ft=ansible:
