---
- name: "Install some packages with pip."
  pip:
    name: "{{ item }}" 
    state: present
  with_items:
    - django
- name: "Install some packages with apt."
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gunicorn
...
# vim: ft=ansible:
