---
# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - run: >
          docker network create rsum || true
      - run: >
          docker run -d --rm --name pg.gc -h pg.gc --network rsum
          -p 5432:5432 postgres:alpine
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "bin/.requirements" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: build container
          command: |
            docker build -t rsum bin
      - run:
          name: run tests
          command: |
            docker run --network rsum --rm -d --name rsum rsum
            docker exec rsum pytest
            docker cp rsum:/tmp/junit.xml /tmp/junit.xml
      - store_test_results:
          path: /tmp/junit.xml
      - store_artifacts:
          path: test-reports
          destination: test-reports
    working_directory: ~/repo
...
