---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: "mrsum"
    command: "/usr/bin/supervisord -n"
    image: ecla/ansible:latest
    ports:
      - "8193:8193"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
...
# vim: ft=ansible:
