---
- name: "mpsql"
  hosts: mpsql
  roles:
    - role: "mpsql"
- name: "mngnx"
  hosts: mngnx
  roles:
    - role: "mngnx"
- name: "converge"
  hosts: mrsum
  roles:
    - role: "mrsum"
- name: "nagios"
  hosts: mngos
  roles:
    - role: "mngos"
...
# vim: ft=ansible:
