---
- name: "psql"
  hosts: mpsql
  roles:
    - role: "psql"
- name: "converge"
  hosts: mrsum
  roles:
    - role:
        "rsum"
- name: "nagios"
  hosts: mngos
  roles:
    - role: "ngos"
...
# vim: ft=ansible:
