---
- name: "psql"
  hosts: mpsql
  roles:
    - role: "mpsql"
- name: "converge"
  hosts: mrsum
  roles:
    - role:
        "mrsum"
- name: "nagios"
  hosts: mngos
  roles:
    - role: "mngos"
...
# vim: ft=ansible:
