---
- name: "psql"
  hosts: mpsql
  tasks:
    - name: "start psql"
      supervisorctl:
        state: "present"
        name: "psql"
- name: "add host"
  hosts: mrsum
  tasks:
    - debug:
        var: hostvars[mpsql]
- name: "converge"
  hosts: mrsum
  roles:
    - role:
        "rsum"
...
# vim: ft=ansible:
