---
- name: "psql"
  hosts: mpsql
  tasks:
    - name: "start psql"
      supervisorctl:
        state: "present"
        name: "psql"
    - name: "Install Nagios."
      apt:
        name: "nagios-nrpe-server"
        state: "present"
        update_cache: "yes"
- name: "converge"
  hosts: mrsum
  roles:
    - role:
        "rsum"
- name: "nagios"
  hosts: mngos
  roles:
    - role: "ngos"
...
# vim: ft=ansible:
