---
- name: "psql"
  hosts: mpsql
  tasks:
    - name: "start psql"
      supervisorctl:
        state: "present"
        name: "psql"
- name: "add host"
  hosts: mrsum
  tasks:
    - name: "add mpsql to hosts file"
      lineinfile:
        dest: /etc/hosts
        line: "mpsql hostvars['mpsql']['ansible_default_ipv4']['address']"
        state: present
- name: "converge"
  hosts: mrsum
  roles:
    - role:
        "rsum"
...
# vim: ft=ansible:
