---
- name: "mrsum"
  src: executive-consultants-of-los-angeles.rsum
  version: "iss57"
- name: "mpsql"
  src: executive-consultants-of-los-angeles.psql
- name: "mngos"
  src: executive-consultants-of-los-angeles.nagios
...
# vim: ft=ansible:
