---
galaxy_info:
  author: "Edward Harris"
  description: "Manage deployment of CV for Edward Harris"
  company: "Executive Consultants of Los Angeles"
  license:
    - Unlicenced
  min_ansible_container_version: 0.9.1
  tags:
    - ecla
    - django
    - cv
...
# vim: ft=ansible:
