---
galaxy_info:
  author: "Edward Harris" 
  description: "Run my CV." 
  company: "ECLA" 

  # If the issue tracker for your role is not on GitHub, uncomment the
  # next line and provide a value
  # issue_tracker_url: 

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: Unlicensed 
  min_ansible_container_version: 0.9.1
  tags:
    - apsql
...
# vim: ft=ansible:
