set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'docker/docker' , {'rtp': '/contrib/syntax/vim/'}
" All of your Plugins must be added before the following line
call vundle#end()  
filetype plugin on

syntax on
set ts=2 sts=2 sw=2 et modeline
Bundle 'wakatime/vim-wakatime'
Bundle 'chase/vim-ansible-yaml'
